# Generated by Django 4.1.2 on 2022-11-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartview', '0002_alter_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Total'),
        ),
    ]
