# Generated by Django 4.1.2 on 2022-11-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookview', '0002_alter_book_price_ht'),
        ('cartview', '0006_alter_cartitem_price_ht_alter_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookview.book', verbose_name='cart_items'),
        ),
    ]
