# Generated by Django 4.1.2 on 2022-11-28 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookview', '0002_alter_book_price_ht'),
        ('cartview', '0007_alter_cartitem_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookview.book', verbose_name='book_in_cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='cartview.cart', verbose_name='Cart'),
        ),
    ]
