# Generated by Django 4.1.2 on 2022-11-28 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartview', '0008_alter_cartitem_book_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookview', to='cartview.cart', verbose_name='Cart'),
        ),
    ]
