# Generated by Django 4.1.2 on 2022-11-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartview', '0009_alter_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_statuses', models.CharField(choices=[('New', 'New Order'), ('In_Progress', 'In Progress'), ('Done', 'Done')], default='New', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=40, verbose_name='First and Last Name')),
                ('address_line1', models.CharField(max_length=60, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=60, verbose_name='Address Line 2')),
                ('town_city', models.CharField(max_length=60, verbose_name='Town/City')),
                ('country', models.CharField(max_length=60, verbose_name='Country')),
                ('phone_number', models.CharField(blank=True, max_length=60, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='cartview.cart', verbose_name='Cart')),
                ('status', models.ForeignKey(blank=True, default='New', on_delete=django.db.models.deletion.PROTECT, to='cartview.orderstatus', verbose_name='Order Status')),
            ],
        ),
    ]
