# Generated by Django 4.1.2 on 2022-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartview', '0010_orderstatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='types_of_statuses',
            field=models.CharField(choices=[('new', 'New Order'), ('in_Progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20, unique=True),
        ),
    ]
