# Generated by Django 4.1.2 on 2022-11-13 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('auth_country', models.CharField(max_length=100, verbose_name='Author Origin')),
                ('auth_note', models.TextField(blank=True, max_length=100, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_category', models.CharField(choices=[('SL', 'On Sale'), ('NA', 'New Arrival'), ('NC', 'No Category')], default='NC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_cover', models.CharField(choices=[('HC', 'Hard Cover'), ('SC', 'Softcover'), ('DJ', 'Dust Jacket')], default='HC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=100, verbose_name='Publisher Name')),
                ('pub_country', models.CharField(max_length=100, verbose_name='Publisher Origin')),
                ('pub_note', models.TextField(blank=True, max_length=100, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Book Image')),
                ('book_name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('book_annotation', models.TextField(max_length=500, verbose_name='Annotation')),
                ('price_ht', models.FloatField(default='1.00', verbose_name='Price of the Book')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('book_aut', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reflib.author', verbose_name='Book Author')),
                ('book_cover', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reflib.cover', verbose_name='Book Cover')),
                ('category', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='reflib.category', verbose_name='Category')),
                ('created_by', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
