# Generated by Django 4.1.2 on 2022-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=100, verbose_name='Publisher Name')),
                ('pub_country', models.CharField(max_length=100, verbose_name='Publisher Origin')),
                ('pub_note', models.TextField(blank=True, max_length=100, null=True, verbose_name='Note')),
            ],
        ),
    ]
