# Generated by Django 4.1.2 on 2022-10-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflib', '0002_author_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='types_of_cover',
            field=models.CharField(choices=[('HC', 'Hard Cover'), ('SC', 'Softcover'), ('DJ', 'Dust Jacket')], default='HC', max_length=2),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Book Image')),
                ('book_name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('book_aut', models.CharField(max_length=100, verbose_name='Book Author')),
                ('book_annotation', models.TextField(max_length=500, verbose_name='Annotation')),
                ('book_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflib.cover')),
            ],
        ),
    ]
