# Generated by Django 4.1.2 on 2022-11-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflib', '0004_remove_category_types_of_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='types_of_categories',
            field=models.CharField(choices=[('SL', 'Sale'), ('NA', 'New Arrival'), ('NC', 'No Category')], default='NC', max_length=2),
        ),
    ]
